service: tetris

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
  environment:
    NODE_ENV: develop

functions:
  render:
    handler: server/lambda.render
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get